### ISSUE TITLE
[Reature Request] Could you add Heroku support?

### ISSUE THREAD

**Issue by erickyun** [danimart1991/jackett2telegram#11]
Hi,

Could you please add heroku?

I tried myself but I couldn't make it work since Im noob.
https://github.com/erickyun/jackett2telegram-2

### EDİT:
İt works in the beginning but after some time
I'm getting this error?
`
Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
`

**Comment by danimart1991** [comment]
Hi @erickyun.

I only used Heroku in its beginnings, but... It seems that support Docker Containers for free. Did you try to deploy the app by this way?

**Comment by erickyun** [comment]
> Hi @erickyun.
> 
> I only used Heroku in its beginnings, but... It seems that support Docker Containers for free. Did you try to deploy the app by this way?

Could you tell me how I don't have much knowledge about docker?

Also do you any plans to add heroku to your repo?

**Comment by DarremMolko** [comment]
I checked your repo and it seems to be failing because you are deploying the bot as a web service. In your heroku.yml you should change the "web" specification to "worker":
```
build:
  docker:
    worker: Dockerfile
```
Anyway heroku has ephemeral storage, even if you manage to make it work once your app restarts you will lose your feeds (because the database is deleted). This could be circumvented by making the bot compatible with the heroku postgres add-on.

**Comment by erickyun** [comment]
> 

Thanks that did indeed fix the error. 
How can I make the bot compatible with the heroku postgres?

**Comment by DarremMolko** [comment]
> > 
> 
> Thanks that did indeed fix the error. How can I make the bot compatible with the heroku postgres?

Unless you know python there's nothing you can do, because it requires some changes to the script. Only Danimart or some other contributor with the necessary knowledge can do this.

**Comment by danimart1991** [comment]
I'm sorry, but I'm not going to implement these features:
- _Heroku_ is a specific deployment system, docker is much more widespread and compatible with Heroku and other deployment systems, that's why it's "included".
- _PostgreSQL_ is a fairly heavy database, actual solution with _SQLite_ it is more than enough. And thanks to _Docker_, persisting this database is extremely easy.
- Finally, I don't have enough knowledge in any of the previous technologies to implement them.

I have seen that [some forks](https://github.com/danimart1991/jackett2telegram/network) have implemented solutions for deployment on _Heroku_. Have you reviewed them?
